version: '3.8'

services:
  planning-poker-client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_SERVER_URL=${SERVER_URL}
        - REACT_APP_VERSION=${REACT_APP_VERSION}
        - REACT_APP_BUILD_HASH=${REACT_APP_BUILD_HASH}
        - REACT_APP_BUILD_BRANCH=${REACT_APP_BUILD_BRANCH}
        - REACT_APP_BUILD_TIME=${REACT_APP_BUILD_TIME}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    container_name: ${CLIENT_CONTAINER_NAME:-planning-poker-client-local}
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-8080}:80"
    networks:
      - local
    environment:
      - NODE_ENV=${NODE_ENV:-production}

  planning-poker-server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    container_name: ${SERVER_CONTAINER_NAME:-planning-poker-server-local}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8081}:${PORT:-3001}"
    networks:
      - local
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - CLIENT_URL=${CLIENT_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - planning-poker-client

networks:
  local:
    driver: bridge